spring:
  datasource:
    url: jdbc:h2:mem:librarydb;INIT=CREATE SCHEMA IF NOT EXISTS library;
    driver-class-name: org.h2.Driver
    username: codegallery
    password: librarian
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect